emqx:
  address: tcp://47.93.10.179:1883
  username: admin
  password: admin
  clientId: iotc-go-client
  topic:
    topicList: iotc/#
    qosList: 2

rabbitmq:
  address: 47.93.10.179:5672
  username: admin
  password: adminaaa
  virtual-host: /
  exchange:
    name: iot-mqtt-exchange
    kind: topic
    durable: false
    autoDelete: false
    internal: false
    noWait: false
  publish:
    basicKey: iotmqtt
    mandatory: false
    immediate: false
    contentType: text/plain
