spring:
  redis:
    database: 0
    password: darius@333
#    url: redis://root:darius@333@47.93.10.179:6379
    host: 47.93.10.179
    port: 6379
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
      timeout: 3000 # 连接超时时间（毫秒）
