
############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
  servlet:
    context-path: /

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  profiles:
    active: dev
  datasource:                                           # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
    username: root
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 512000     # 文件上传大小限制为500kb
      max-request-size: 512000  # 请求大小限制为500kb
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
  redis:
    database: 0
    password:
    #    url: redis://root:darius@333@47.93.10.179:6379
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
      timeout: 3000 # 连接超时时间（毫秒）


############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: ccuiot.iotc.ccuiot.iotc.pojo        # 所有POJO类所在包路径
  mapper-locations: classpath:ccuiot.iotc.ccuiot.iotc.my.mapper/*.xml      # mapper映射文件


############################################################
#
# mybatis ccuiot.iotc.ccuiot.iotc.my.mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  mappers: yx.graduation.elec.my.mapper.MyMapper
  not-empty: false    # 在进行数据库操作的的时候，判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL
# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
