# 生产环境
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iotc?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    password: root
  thymeleaf:
    cache: false

logging:
  level:
    ccuiot.iotc.mapper: debug
