# 生产环境
server:
  port: 8180

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/iotc?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    password: root

  thymeleaf:
    cache: false

  redis:
    database: 1
    password: root
    host: 127.0.0.1
    port: 6379

  rabbitmq:
    addresses: 127.0.0.1:5672
    username: admin
    password: admin
    virtual-host: /
  jmx:
    enabled: false

#logging:
#  level:
#    ccuiot.iotc.mapper: debug
