# 开发环境
server:
  port: 8180

spring:
  datasource:
    url: jdbc:mysql://192.168.38.131:3306/iotc?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    password: root

  thymeleaf:
    cache: false

  redis:
    database: 0
    password: root
    host: 192.168.38.131
    port: 6379

  rabbitmq:
    addresses: 192.168.38.131:5672
    username: admin
    password: admin
    virtual-host: /

logging:
  level:
    ccuiot.iotc.mapper: debug
